name: Deploy to GitHub Pages

on:
  push:
    branches: [main]         # ← main ブランチに push したら実行

permissions:
  contents: write            # gh-pages へ push する権限

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node を用意 (Astro 3 以降は 18+ で OK)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - name: Add .nojekyll
        run: echo "" > dist/.nojekyll

      # ⭐ 公式 deploy Action（ビルド＋gh-pages push を全部やってくれる）
      - uses: withastro/action@v2      # v2 は 2025-05 リリース
        with:
          deploy-branch: gh-pages      # ← GitHub Pages 既定
          node-version: 20
