name: Deploy to GitHub Pages

on:
  push:
    branches: [main]   # main に push したら自動デプロイ

permissions:
  contents: read       # 必須
  pages: write         # GitHub Pages へ書き込み
  id-token: write      # OIDC（deploy-pages 用）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ★ これ 1 行で「Node セットアップ → 依存解決 → Astro build →
      #    .nojekyll 追加 → gh-pages ブランチへ push (pages artifact)」までやる
      - uses: withastro/action@v4   # v4 (= 2025-03 リリース)
        with:
          node-version: 20         # 任意。省略すると v22 が入る
          deploy-branch: gh-pages  # 変更したい場合のみ
